# Global constants
skeleton:
  year: {start: 1990, end: 2021}
  age: {start: 0, end: 85}
  sex: {Male: 'Male', Female: 'Female'}
  regions: [
'BI',
'KM',
'DJ',
'ER',
'ET',
'KE',
'MG',
'MW',
'MU',
'YT',
'MZ',
'RE',
'RW',
'SC',
'SO',
'SS',
'UG',
'TZ',
'ZM',
'ZW',
'AO',
'CM',
'CF',
'TD',
'CG',
'CD',
'GQ',
'GA',
'ST',
'DZ',
'EG',
'LY',
'MA',
'SD',
'TN',
'EH',
'BW',
'SZ',
'LS',
'NA',
'ZA',
'BJ',
'BF',
'CV',
'CI',
'GM',
'GH',
'GN',
'GW',
'LR',
'ML',
'MR',
'NE',
'NG',
'SH',
'SN',
'SL',
'TG',
'KZ',
'KG',
'TJ',
'TM',
'UZ',
'CN',
'HK',
'MO',
'TW',
'KP',
'JP',
'MN',
'KR',
'AF',
'BD',
'BT',
'IN',
'IR',
'MV',
'NP',
'PK',
'LK',
'BN',
'KH',
'ID',
'LA',
'MY',
'MM',
'PH',
'SG',
'TH',
'TL',
'VN',
'AM',
'AZ',
'BH',
'CY',
'GE',
'IQ',
'IL',
'JO',
'KW',
'LB',
'OM',
'QA',
'SA',
'PS',
'SY',
'TR',
'AE',
'YE',
'BY',
'BG',
'CZ',
'HU',
'PL',
'MD',
'RO',
'RU',
'SK',
'UA',
'DK',
'EE',
'FO',
'FI',
'GG',
'IS',
'IE',
'IM',
'JE',
'LV',
'LT',
'NO',
'SE',
'GB',
'AL',
'AD',
'BA',
'HR',
'GI',
'GR',
'VA',
'IT',
'XK',
'MT',
'ME',
'MK',
'PT',
'SM',
'RS',
'SI',
'ES',
'AT',
'BE',
'FR',
'DE',
'LI',
'LU',
'MC',
'NL',
'CH',
'AI',
'AG',
'AW',
'BS',
'BB',
'BQ',
'VG',
'KY',
'CU',
'CW',
'DM',
'DO',
'GD',
'GP',
'HT',
'JM',
'MQ',
'MS',
'PR',
'BL',
'KN',
'LC',
'MF',
'VC',
'SX',
'TT',
'TC',
'VI',
'BZ',
'CR',
'SV',
'GT',
'HN',
'MX',
'NI',
'PA',
'AR',
'BO',
'BR',
'CL',
'CO',
'EC',
'FK',
'GF',
'GY',
'PY',
'PE',
'SR',
'UY',
'VE',
'BM',
'CA',
'GL',
'PM',
'US',
'AU',
'NZ',
'FJ',
'NC',
'PG',
'SB',
'VU',
'GU',
'KI',
'MH',
'FM',
'NR',
'MP',
'PW',
'AS',
'CK',
'PF',
'NU',
'WS',
'TK',
'TO',
'TV',
'WF'
]
# figure specifications
figspec:
  dimensions: { width: 180 }
  colors:
    sex: { 'Male': '#004b87', 'Female': '#c60c30' }
